# Generated by Django 4.0.4 on 2022-04-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('courseCode', models.CharField(max_length=10)),
                ('isTheory', models.BooleanField()),
            ],
        ),
    ]
