# Generated by Django 4.0.4 on 2022-04-21 06:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_period_courseteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='courseTeachers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
